# Generated by Django 3.1.5 on 2021-01-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=255, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Пароль')),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Раздатка'),
        ),
    ]
